INSERT INTO points(map_id, title, description, image, long, lat) VALUES (1, 'Coffee 23', 'Cafe 23 is an independent coffee shop located just steps away from Trinity Bellwoods, ready to fill your coffee void. It has pastries sourced from local bakeries, and ample seating out back on the patio or out front peering out to Queen West.', 'https://media.blogto.com/listings/20190816_Business-6.jpg?w=2048&cmd=resize_then_crop&height=1365&quality=70', 43.65, -79.41);

INSERT INTO points(map_id, title, description, image, long, lat) VALUES (1, 'Hale', 'Hale Coffee is a roastery and coffee shop in the Junction Triangle neighbourhood, in the Clock Factory building that houses a mix of artists’ studios, businesses, fitness clubs, and more, and hosts other venerable Toronto coffee juggernaut Station Cold Brew.', 'https://cdn.shopify.com/s/files/1/0299/0528/9275/t/5/assets/novembershoot-07337_1920x1280_crop_center.jpg', 43.67, -79.45);
INSERT INTO points(map_id, title, description, image, long, lat) VALUES (1, 'Ethica', 'Ethica Coffee Roasters serves coffees roasted in full view of an industrial cafe space. The cafe specializes in single origin specialty coffees roasted in a European style using a small Dutch Giesen roaster.', 'https://media.blogto.com/listings/20200205-EthicaCoffee16.jpg?w=2048&cmd=resize_then_crop&height=1365&quality=70', 43.66, -79.45);

INSERT INTO points(map_id, title, description, image, long, lat) VALUES (2, 'Indigo on Bay', 'This downtown location at the Manulife Centre is widely accepted as one of the best in town. Not only is it easy to get to, its big glass windows are mesmerizing at night and it just got a refreshing makeover.', 'https://media.blogto.com/articles/2022329-indigo.jpg?w=2048&cmd=resize_then_crop&height=1365&quality=70', 43.67, -79.39);

INSERT INTO points(map_id, title, description, image, long, lat) VALUES (3, 'Bandit Brewery', 'Bandit Brewery is an open-concept brewery, taproom and patio located inside a former auto shop at Dundas and Roncesvalles. Expect to find 20 beers on tap, including 15 original brews and a handful showcasing fellow craft brewers.', 'https://media.blogto.com/uploads/2022/11/14/1668459805-20221114-bandit-4.jpeg?w=1400&cmd=resize&height=2500&quality=70', 43.65, -79.45);

INSERT INTO points(map_id, title, description, image, long, lat) VALUES (4, 'Woodbine Beach', 'The largest of the four beaches that line Lake Ontario, this stretch of sandy waterfront pulses on hot summer days, playing host to frolicking children, gleaming sunbathers, barbecuers, and volleyball players galore.', 'https://media.blogto.com/articles/20190708-woodbine-beach-16.jpg?w=2048&cmd=resize_then_crop&height=1365&quality=70', 43.66, -79.31);
