DROP TABLE IF EXISTS FavoriteMapping CASCADE;
CREATE TABLE FavoriteMapping (
    favorite_id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    map_id INTEGER REFERENCES maps(id) ON DELETE CASCADE NOT NULL
);
